# .github/workflows/tf.yml
name: 'Terraform Deployment'

on:
  push:
    branches: [ main, master ]
    paths:
      - '*.tf'
      - '.github/workflows/terraform_action.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - '*.tf'
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: 'Destroy infrastructure'
        default: true
      environment:
        type: choice
        description: 'Select environment'
        options:
          - dev
          - prod
        default: 'dev'

jobs:
  terraform:
    uses: clouddrove/github-shared-workflows/.github/workflows/terraform_workflow.yml@master
    with:
      working_directory: '.'  # Root directory since terraform files are in root
      provider: 'aws'
      aws_region: 'us-east-1'
      timeout: 5
      approvers: ruchit-sharma09
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}